import React from 'react';

const BundleBox = ({ data }) => {
  if (!data) {
    return (
      <div className="bg-card border border-border rounded-2xl p-8 text-center text-muted-foreground font-medium">
        No recommendations available
      </div>
    );
  }

  const bundleItems = Array.isArray(data.bundle) ? data.bundle : [];
  const factors = Array.isArray(data.factors) ? data.factors : [];
  const hasDecisionInfo = Boolean(data.decision || data.ai_explanation || data.regret_risk || factors.length);

  const getLabelStyles = (label) => {
    switch (label) {
      case 'GOOD':
        return 'bg-green-500/10 text-green-400 border-green-500/20';
      case 'OVERHYPED':
        return 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20';
      case 'AVOID':
        return 'bg-red-500/20 text-destructive border-red-500/40';
      default:
        return 'bg-gray-500/10 text-gray-400 border-gray-500/20';
    }
  };

  return (
    <div className="flex flex-col gap-8 animate-in fade-in slide-in-from-bottom-4 duration-700 ease-out">
      {/* FINAL RECOMMENDATION DECISION */}
      {hasDecisionInfo && (
        <div className="bg-primary/10 border border-primary/20 rounded-xl p-5 flex flex-col gap-3 shadow-[0_4px_24px_rgba(173,70,255,0.05)]">
          <h2 className="text-xl font-extrabold text-foreground tracking-tight">
            Final Recommendation: <span className="text-primary uppercase tracking-widest">{data.decision || 'N/A'}</span>
          </h2>
          <p className="text-foreground font-medium leading-relaxed">
            {data.ai_explanation || 'No explanation available'}
          </p>
          
          <div className="flex flex-col gap-3 mt-1">
            {data.regret_risk && (
              <div className="text-xs font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-muted-foreground"></div>
                Regret Risk: <span className="text-foreground font-extrabold">{data.regret_risk}</span>
              </div>
            )}
            
            <div className="pt-3 border-t border-primary/20">
              <p className="text-xs font-bold text-muted-foreground uppercase mb-2">Factors considered:</p>
              {factors.length > 0 ? (
                <ul className="text-xs text-muted-foreground list-disc pl-4 space-y-1.5">
                  {factors.map((factor, index) => (
                    <li key={`${factor}-${index}`}>{factor}</li>
                  ))}
                </ul>
              ) : (
                <p className="text-xs text-muted-foreground">No factors available</p>
              )}
            </div>
          </div>
          
          <div className="mt-2 pt-2 text-[10px] text-muted-foreground uppercase tracking-widest flex items-center gap-2">
             <span className="w-1.5 h-1.5 bg-primary/80 rounded-full animate-pulse shadow-[0_0_8px_var(--primary-ai)]"></span>
             <span className="animate-pulse">Decision generated by AI model</span>
          </div>
        </div>
      )}

      {/* AI BUNDLE ANALYSIS */}
      <div className="bg-card border border-border rounded-2xl shadow-sm overflow-hidden">
        <div className="p-6 border-b border-border bg-background/50 flex items-center justify-between">
           <div className="flex items-center gap-3">
             <div className="w-2 h-2 rounded-full bg-primary animate-pulse shadow-[0_0_8px_rgba(173,70,255,0.8)]"></div>
             <h3 className="font-bold text-foreground text-lg uppercase tracking-wider">AI Bundle Analysis</h3>
           </div>
           {typeof data.confidence === 'number' && (
             <span className="text-sm font-semibold text-muted-foreground bg-white/[0.03] px-3 py-1 rounded-full border border-border shadow-sm">
               Confidence: {data.confidence}%
             </span>
           )}
        </div>
        {bundleItems.length > 0 ? (
          <ul className="divide-y divide-border">
            {bundleItems.map((item, index) => (
              <li
                key={`${item.name}-${index}`}
                className="p-5 flex flex-col gap-2 hover:bg-white/[0.02] transition-colors animate-in fade-in slide-in-from-bottom-2 duration-500"
                style={{ animationDelay: `${index * 150}ms`, animationFillMode: 'both' }}
              >
                <div className="flex items-center justify-between w-full">
                  <span className="text-foreground font-medium">{item.name}</span>
                  <span className={`px-3 py-1.5 text-xs font-bold rounded-full border shadow-sm tracking-wide ${getLabelStyles(item.label)}`}>
                    {item.label}
                  </span>
                </div>
                {item.reason && (
                  <p className="text-sm text-muted-foreground leading-relaxed mt-1">
                    {item.reason}
                  </p>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <div className="p-5 text-sm text-muted-foreground">No bundle recommendations available</div>
        )}
      </div>
    </div>
  );
};

export default BundleBox;
